<?php

/**
 * @file
 * Functions to support theming in the classy_subtheme theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function classy_subtheme_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function classy_subtheme_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function classy_subtheme_preprocess_node(&$variables) {

}
